
sudo: required
dist: trusty

language: c

before_install:
  # Get cmake v3.5
  - |
    DEPS_DIR="${TRAVIS_BUILD_DIR}/deps"
    mkdir ${DEPS_DIR} && cd ${DEPS_DIR}
    CMAKE_URL="https://cmake.org/files/v3.5/cmake-3.5.2-Linux-x86_64.tar.gz"
    mkdir cmake && travis_retry wget --no-check-certificate --quiet -O - ${CMAKE_URL} | tar --strip-components=1 -xz -C cmake
    export PATH=${DEPS_DIR}/cmake/bin:${PATH}
    cd ..

  # Pystache needed for generation of MourOS diagnostic code
  - sudo pip install pystache

  # Create the build directories
  - |
    mkdir build
    mkdir build/install

install:
  # Install libopencm3
  - ./libsrc/mouros/build_libopencm3.sh ./build/install

before_script:
  # Generate the makefiles
  - mkdir build/ratfist
  - cd build/ratfist
  - cmake -DCMAKE_INSTALL_PREFIX=../install -DCMAKE_TOOLCHAIN_FILE=../../libsrc/mouros/cmake/arm-none-eabi-toolchain.cmake -DCHIP_FAMILY=STM32F0 -DCMAKE_BUILD_TYPE=Debug -DUSE_FULL_NEWLIB=ON ../..


script:
  # Build it
  - cmake --build . --clean-first
  # And the docs
  - cmake --build . --target ratfist-doc


addons:
  apt:
    packages:
      # arm-none-eabi gcc & newlib
      - gcc-arm-none-eabi
      - libnewlib-arm-none-eabi
      # Documentation tools
      - doxygen
      - graphviz
