
dist: bionic

language: c

before_install:
  - arm-none-eabi-gcc --version

  # Get rust
  - curl https://sh.rustup.rs -sSf | sh -s -- -y --default-toolchain nightly
  - export PATH=~/.cargo/bin:${PATH}
  - rustup component add rust-src
  - rustup component add --target thumbv6m-none-eabi rust-std
  - rustup component add --target thumbv7em-none-eabihf rust-std
  - rustc --version

  # Pystache needed for generation of MourOS diagnostic code
  - sudo pip install pystache

  # Needed for generation of coverage reports
  - sudo pip install gcovr

  # Create the build directories
  - |
    mkdir build
    mkdir build/install


install:
  # Install libopencm3
  - ./libsrc/mouros/build_libopencm3.sh ./build/install

before_script:
  # Generate the makefiles
  - |
    mkdir build/ratfist
    mkdir build/ratfist-tests

  - cd build/ratfist
  - cmake -DCMAKE_INSTALL_PREFIX=../install -DCMAKE_TOOLCHAIN_FILE=../../libsrc/mouros/cmake/arm-none-eabi-toolchain.cmake -DCHIP_FAMILY=${CHIP_FAMILY} -DBOARD_TYPE=${BOARD_TYPE} -DCMAKE_BUILD_TYPE=${BUILD_TYPE} -DUSE_FULL_NEWLIB=ON -DINCLUDE_SPINNER=${INCLUDE_SPINNER} -DINCLUDE_METEO=${INCLUDE_METEO} ../..
  - cd ../..

  - cd build/ratfist-tests
  - cmake -DCMAKE_INSTALL_PREFIX=../install -DCMAKE_TOOLCHAIN_FILE=../../libsrc/mouros/cmake/gcc-linux-x86-toolchain.cmake -DCMAKE_BUILD_TYPE=${BUILD_TYPE} -DBOARD_TYPE=${BOARD_TYPE} ../../tests
  - cd ../..



script:
  # Build it
  - cmake --build build/ratfist --clean-first
  # And the docs
  - cmake --build build/ratfist --target ratfist-doc
  # Install them so that the tests can find them
  - cmake --build build/ratfist --target install
  # Build & run tests
  - cd build/ratfist-tests
  - cmake --build . --clean-first
  - ctest -V .
  - cd ../..
  # Generate coverage
  - cmake --build build/ratfist-tests --target coverage



addons:
  apt:
    packages:
      - cmake
      - gcc-arm-none-eabi
      # 32 bit compiler used for compiling tests
      - gcc-multilib
      # Documentation tools
      - doxygen
      - graphviz

env:
  - |
    CHIP_FAMILY=STM32F0
    BOARD_TYPE=stm32f072discovery
    BUILD_TYPE=Debug
    INCLUDE_SPINNER=1
    INCLUDE_METEO=0
  - |
    CHIP_FAMILY=STM32F0
    BOARD_TYPE=stm32f072discovery
    BUILD_TYPE=Release
    INCLUDE_SPINNER=1
    INCLUDE_METEO=0
  - |
    CHIP_FAMILY=STM32F4
    BOARD_TYPE=stm32f411discovery
    BUILD_TYPE=Debug
    INCLUDE_SPINNER=1
    INCLUDE_METEO=1
  - |
    CHIP_FAMILY=STM32F4
    BOARD_TYPE=stm32f411discovery
    BUILD_TYPE=Release
    INCLUDE_SPINNER=1
    INCLUDE_METEO=1
